In [1]:
import pandas as pd


df = pd.read_csv("sampledata.csv")
df

FileNotFoundError: [Errno 2] No such file or directory: 'sampledata.csv'

In [110]:
df.to_csv('sampledata_2.csv',index=True)

In [111]:
df = pd.read_csv('sampledata_2.csv', index_col=0)
df

   Column1  Column2 Column3  Column4  Column5
0        1       78       A    -0.61    False
1        2       94       C    -0.90     True
2        3       59       B    -0.17     True
3        4       32       C    -2.74    False
4        5       65       B     1.14     True
5        6       94       D    -0.76     True
6        7       21       A    -1.48    False
7        8       74       D    -0.37     True
8        9       37       D     1.00    False
9       10       27       A    -0.27     True

#pandas dataframe manipulation:
DataFrame manipulation in Pandas involves editing and modifying existing DataFrames. Some common DataFrame manipulation operations are:

1.Adding rows/columns
2.Removing rows/columns
3.Renaming rows/columns

Above table contain the Nan columns , no value so we do:

In [112]:
df.columns

Index(['Column1', 'Column2', 'Column3', 'Column4', 'Column5'], dtype='str')

In [113]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  10 non-null     int64
 1   Column2  10 non-null     int64
 2   Column3  10 non-null     str
 3   Column4  10 non-null     float64
 4   Column5  10 non-null     bool
dtypes: bool(1), float64(1), int64(2), str(1)
memory usage: 472.0 bytes

In [114]:
df.shape

(10, 5)

In [115]:
df.mode(0)

   Column1  Column2 Column3  Column4 Column5
0        1     94.0       A    -2.74    True
1        2      NaN       D    -1.48     NaN
2        3      NaN     NaN    -0.90     NaN
3        4      NaN     NaN    -0.76     NaN
4        5      NaN     NaN    -0.61     NaN
5        6      NaN     NaN    -0.37     NaN
6        7      NaN     NaN    -0.27     NaN
7        8      NaN     NaN    -0.17     NaN
8        9      NaN     NaN     1.00     NaN
9       10      NaN     NaN     1.14     NaN

In [116]:
df.dtypes

Column1      int64
Column2      int64
Column3        str
Column4    float64
Column5       bool
dtype: object

In [117]:
# df.describe() # Statistical Summary of Numerical Columns
df.describe(include="bool") # Statistical Summary of Categorical Columns

       Column5
count       10
unique       2
top       True
freq         6

In [118]:
df

   Column1  Column2 Column3  Column4  Column5
0        1       78       A    -0.61    False
1        2       94       C    -0.90     True
2        3       59       B    -0.17     True
3        4       32       C    -2.74    False
4        5       65       B     1.14     True
5        6       94       D    -0.76     True
6        7       21       A    -1.48    False
7        8       74       D    -0.37     True
8        9       37       D     1.00    False
9       10       27       A    -0.27     True

In [119]:
# 1.removing columns:
df = df.drop(columns=["Column4"]) # To drop columns
df = df.drop([4,9]) # To drop rows
df

   Column1  Column2 Column3  Column5
0        1       78       A    False
1        2       94       C     True
2        3       59       B     True
3        4       32       C    False
5        6       94       D     True
6        7       21       A    False
7        8       74       D     True
8        9       37       D    False

In [120]:
df.columns  #give the names of the columns

Index(['Column1', 'Column2', 'Column3', 'Column5'], dtype='str')

In [121]:
df.info()

<class 'pandas.DataFrame'>
Index: 8 entries, 0 to 8
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  8 non-null      int64
 1   Column2  8 non-null      int64
 2   Column3  8 non-null      str
 3   Column5  8 non-null      bool
dtypes: bool(1), int64(2), str(1)
memory usage: 273.0 bytes

In [122]:
df.shape  #number of rows and columns

(8, 4)

In [123]:
df.describe()  #gives the statistical summary of the data

       Column1    Column2
count   8.0000   8.000000
mean    5.0000  61.125000
std     2.9277  28.427539
min     1.0000  21.000000
25%     2.7500  35.750000
50%     5.0000  66.500000
75%     7.2500  82.000000
max     9.0000  94.000000

In [124]:
df

   Column1  Column2 Column3  Column5
0        1       78       A    False
1        2       94       C     True
2        3       59       B     True
3        4       32       C    False
5        6       94       D     True
6        7       21       A    False
7        8       74       D     True
8        9       37       D    False

In [125]:
#2.Adding a new column:
names = [
    "Ekrishna", "Ram", "Nishan", "Sita", "Bibek", "Aarav", "Ujjwal","Shyam"
    ]
df["Names"]=names  # add a new column Names from the list named varibale names.
df
# df = df.drop(columns=['Ujjwal'])
# df

   Column1  Column2 Column3  Column5     Names
0        1       78       A    False  Ekrishna
1        2       94       C     True       Ram
2        3       59       B     True    Nishan
3        4       32       C    False      Sita
5        6       94       D     True     Bibek
6        7       21       A    False     Aarav
7        8       74       D     True    Ujjwal
8        9       37       D    False     Shyam

In [126]:

df["Age"]=[52,25,16,18,56,23,26,25]  # add a new column Names from the list named varibale names.
df

   Column1  Column2 Column3  Column5     Names  Age
0        1       78       A    False  Ekrishna   52
1        2       94       C     True       Ram   25
2        3       59       B     True    Nishan   16
3        4       32       C    False      Sita   18
5        6       94       D     True     Bibek   56
6        7       21       A    False     Aarav   23
7        8       74       D     True    Ujjwal   26
8        9       37       D    False     Shyam   25

In [127]:
names = [
    "Ekrishna", "Ram", "Nishan", "Sita", "Bibek", "Aarav", "Ujjwal","Shyam"
    ]
df.insert(1,"Names2", names)
df

   Column1    Names2  Column2 Column3  Column5     Names  Age
0        1  Ekrishna       78       A    False  Ekrishna   52
1        2       Ram       94       C     True       Ram   25
2        3    Nishan       59       B     True    Nishan   16
3        4      Sita       32       C    False      Sita   18
5        6     Bibek       94       D     True     Bibek   56
6        7     Aarav       21       A    False     Aarav   23
7        8    Ujjwal       74       D     True    Ujjwal   26
8        9     Shyam       37       D    False     Shyam   25

In [128]:
# set the 'Name' column as index
# df.set_index('Column1', inplace=True)
df = df.set_index('Column1')

df

           Names2  Column2 Column3  Column5     Names  Age
Column1
1        Ekrishna       78       A    False  Ekrishna   52
2             Ram       94       C     True       Ram   25
3          Nishan       59       B     True    Nishan   16
4            Sita       32       C    False      Sita   18
6           Bibek       94       D     True     Bibek   56
7           Aarav       21       A    False     Aarav   23
8          Ujjwal       74       D     True    Ujjwal   26
9           Shyam       37       D    False     Shyam   25

In [129]:
df.columns

Index(['Names2', 'Column2', 'Column3', 'Column5', 'Names', 'Age'], dtype='str')

In [130]:
df.reset_index(inplace=True)
df

   Column1    Names2  Column2 Column3  Column5     Names  Age
0        1  Ekrishna       78       A    False  Ekrishna   52
1        2       Ram       94       C     True       Ram   25
2        3    Nishan       59       B     True    Nishan   16
3        4      Sita       32       C    False      Sita   18
4        6     Bibek       94       D     True     Bibek   56
5        7     Aarav       21       A    False     Aarav   23
6        8    Ujjwal       74       D     True    Ujjwal   26
7        9     Shyam       37       D    False     Shyam   25

In [131]:
df.columns

Index(['Column1', 'Names2', 'Column2', 'Column3', 'Column5', 'Names', 'Age'], dtype='str')

In [132]:
df.reset_index(inplace=True)
df

   index  Column1    Names2  Column2 Column3  Column5     Names  Age
0      0        1  Ekrishna       78       A    False  Ekrishna   52
1      1        2       Ram       94       C     True       Ram   25
2      2        3    Nishan       59       B     True    Nishan   16
3      3        4      Sita       32       C    False      Sita   18
4      4        6     Bibek       94       D     True     Bibek   56
5      5        7     Aarav       21       A    False     Aarav   23
6      6        8    Ujjwal       74       D     True    Ujjwal   26
7      7        9     Shyam       37       D    False     Shyam   25

In [133]:
df.columns

Index(['index', 'Column1', 'Names2', 'Column2', 'Column3', 'Column5', 'Names',
       'Age'],
      dtype='str')

In [134]:
df

   index  Column1    Names2  Column2 Column3  Column5     Names  Age
0      0        1  Ekrishna       78       A    False  Ekrishna   52
1      1        2       Ram       94       C     True       Ram   25
2      2        3    Nishan       59       B     True    Nishan   16
3      3        4      Sita       32       C    False      Sita   18
4      4        6     Bibek       94       D     True     Bibek   56
5      5        7     Aarav       21       A    False     Aarav   23
6      6        8    Ujjwal       74       D     True    Ujjwal   26
7      7        9     Shyam       37       D    False     Shyam   25

In [135]:
df.set_index("Names", inplace=True)
df

          index  Column1    Names2  Column2 Column3  Column5  Age
Names
Ekrishna      0        1  Ekrishna       78       A    False   52
Ram           1        2       Ram       94       C     True   25
Nishan        2        3    Nishan       59       B     True   16
Sita          3        4      Sita       32       C    False   18
Bibek         4        6     Bibek       94       D     True   56
Aarav         5        7     Aarav       21       A    False   23
Ujjwal        6        8    Ujjwal       74       D     True   26
Shyam         7        9     Shyam       37       D    False   25

In [136]:
df.columns

Index(['index', 'Column1', 'Names2', 'Column2', 'Column3', 'Column5', 'Age'], dtype='str')

In [137]:
df.drop(columns=['Names2'], inplace=True)
df

          index  Column1  Column2 Column3  Column5  Age
Names
Ekrishna      0        1       78       A    False   52
Ram           1        2       94       C     True   25
Nishan        2        3       59       B     True   16
Sita          3        4       32       C    False   18
Bibek         4        6       94       D     True   56
Aarav         5        7       21       A    False   23
Ujjwal        6        8       74       D     True   26
Shyam         7        9       37       D    False   25

In [189]:
df.drop(columns=['index'], inplace=True)
df

        Column1 Column2 Column3 Column5   Age
Names
Ram         2.0       A       A    True  25.0
Nishan      3.0    59.0       B    True  16.0
Sita        4.0    32.0       C   False  18.0
Bibek       6.0    94.0       D    True  56.0
Aarav       7.0    21.0       A   False  23.0
Shyam       9.0    37.0       D   False  25.0
Puja        9.5       B      10    True  10.0
ABC         8.0    10.0      10    True  10.0
Sunita      5.0    10.0      10      10  10.0
Def        10.0    10.0      10      10  10.0

In [138]:
# loc => Location
# iloc => Integer Location
print(df.loc["Nishan":"Ujjwal"])
print()
print()
df.iloc[1:6:1]

        index  Column1  Column2 Column3  Column5  Age
Names
Nishan      2        3       59       B     True   16
Sita        3        4       32       C    False   18
Bibek       4        6       94       D     True   56
Aarav       5        7       21       A    False   23
Ujjwal      6        8       74       D     True   26

        index  Column1  Column2 Column3  Column5  Age
Names
Ram         1        2       94       C     True   25
Nishan      2        3       59       B     True   16
Sita        3        4       32       C    False   18
Bibek       4        6       94       D     True   56
Aarav       5        7       21       A    False   23

In [139]:
print(df.iloc[3])
print()
print()
df.iloc[3:7:2]

index          3
Column1        4
Column2       32
Column3        C
Column5    False
Age           18
Name: Sita, dtype: object

       index  Column1  Column2 Column3  Column5  Age
Names
Sita       3        4       32       C    False   18
Aarav      5        7       21       A    False   23

.loc[] is used to access or modify rows and columns in a DataFrame by label (name) — not by position.

In [140]:
df.iloc[1, 0] = 50    
df.loc['Puja', 'Column2'] = 50
df.loc['Puja', 'Column1'] = 9.5
df.loc['Puja', 'Column5'] = True
df.loc['Ujjwal', 'Column5'] = False # Adding new entries in the dataset
df.loc['ABC', 'Column5'] = True
print(df)
print(df.loc["Ekrishna":"Sita"])
print(df.iloc[0:5])
print(df.loc["Ujjwal"]) # Accessing the newly added entries

          index  Column1  Column2 Column3 Column5   Age
Names
Ekrishna    0.0      1.0     78.0       A   False  52.0
Ram        50.0      2.0     94.0       C    True  25.0
Nishan      2.0      3.0     59.0       B    True  16.0
Sita        3.0      4.0     32.0       C   False  18.0
Bibek       4.0      6.0     94.0       D    True  56.0
Aarav       5.0      7.0     21.0       A   False  23.0
Ujjwal      6.0      8.0     74.0       D   False  26.0
Shyam       7.0      9.0     37.0       D   False  25.0
Puja        NaN      9.5     50.0     NaN    True   NaN
ABC         NaN      NaN      NaN     NaN    True   NaN
          index  Column1  Column2 Column3 Column5   Age
Names
Ekrishna    0.0      1.0     78.0       A   False  52.0
Ram        50.0      2.0     94.0       C    True  25.0
Nishan      2.0      3.0     59.0       B    True  16.0
Sita        3.0      4.0     32.0       C   False  18.0
          index  Column1  Column2 Column3 Column5   Age
Names
Ekrishna    0.0      1.0     78.0       A   False  52.0
Ram        50.0      2.0     94.0       C    True  25.0
Nishan      2.0      3.0     59.0       B    True  16.0
Sita        3.0      4.0     32.0       C   False  18.0
Bibek       4.0      6.0     94.0       D    True  56.0
index        6.0
Column1      8.0
Column2     74.0
Column3        D
Column5    False
Age         26.0
Name: Ujjwal, dtype: object

In [141]:
df

          index  Column1  Column2 Column3 Column5   Age
Names
Ekrishna    0.0      1.0     78.0       A   False  52.0
Ram        50.0      2.0     94.0       C    True  25.0
Nishan      2.0      3.0     59.0       B    True  16.0
Sita        3.0      4.0     32.0       C   False  18.0
Bibek       4.0      6.0     94.0       D    True  56.0
Aarav       5.0      7.0     21.0       A   False  23.0
Ujjwal      6.0      8.0     74.0       D   False  26.0
Shyam       7.0      9.0     37.0       D   False  25.0
Puja        NaN      9.5     50.0     NaN    True   NaN
ABC         NaN      NaN      NaN     NaN    True   NaN

In [142]:
df.loc["Ram","Column3"]="A"
df.loc["Ram"]

index      50.0
Column1     2.0
Column2    94.0
Column3       A
Column5    True
Age        25.0
Name: Ram, dtype: object

In [143]:
df

          index  Column1  Column2 Column3 Column5   Age
Names
Ekrishna    0.0      1.0     78.0       A   False  52.0
Ram        50.0      2.0     94.0       A    True  25.0
Nishan      2.0      3.0     59.0       B    True  16.0
Sita        3.0      4.0     32.0       C   False  18.0
Bibek       4.0      6.0     94.0       D    True  56.0
Aarav       5.0      7.0     21.0       A   False  23.0
Ujjwal      6.0      8.0     74.0       D   False  26.0
Shyam       7.0      9.0     37.0       D   False  25.0
Puja        NaN      9.5     50.0     NaN    True   NaN
ABC         NaN      NaN      NaN     NaN    True   NaN

In [144]:
df.loc["Ujjwal","Column1"]=11
df.loc["Ujjwal","Column2"]=33
df.loc["Ujjwal"]

index        6.0
Column1     11.0
Column2     33.0
Column3        D
Column5    False
Age         26.0
Name: Ujjwal, dtype: object

In [145]:
df

          index  Column1  Column2 Column3 Column5   Age
Names
Ekrishna    0.0      1.0     78.0       A   False  52.0
Ram        50.0      2.0     94.0       A    True  25.0
Nishan      2.0      3.0     59.0       B    True  16.0
Sita        3.0      4.0     32.0       C   False  18.0
Bibek       4.0      6.0     94.0       D    True  56.0
Aarav       5.0      7.0     21.0       A   False  23.0
Ujjwal      6.0     11.0     33.0       D   False  26.0
Shyam       7.0      9.0     37.0       D   False  25.0
Puja        NaN      9.5     50.0     NaN    True   NaN
ABC         NaN      NaN      NaN     NaN    True   NaN

In [146]:
df.loc["Aarav":"Ujjwal"]

        index  Column1  Column2 Column3 Column5   Age
Names
Aarav     5.0      7.0     21.0       A   False  23.0
Ujjwal    6.0     11.0     33.0       D   False  26.0

In [147]:
df.iloc[5:9]

        index  Column1  Column2 Column3 Column5   Age
Names
Aarav     5.0      7.0     21.0       A   False  23.0
Ujjwal    6.0     11.0     33.0       D   False  26.0
Shyam     7.0      9.0     37.0       D   False  25.0
Puja      NaN      9.5     50.0     NaN    True   NaN

In [148]:
df.iloc[0,0] = 5.0
df.iloc[[0,6]]

          index  Column1  Column2 Column3 Column5   Age
Names
Ekrishna    5.0      1.0     78.0       A   False  52.0
Ujjwal      6.0     11.0     33.0       D   False  26.0

In [149]:
df.describe(include='all')

            index    Column1    Column2 Column3 Column5        Age
count    8.000000   9.000000   9.000000       8      10   8.000000
unique        NaN        NaN        NaN       4       2        NaN
top           NaN        NaN        NaN       A   False        NaN
freq          NaN        NaN        NaN       3       5        NaN
mean    10.250000   5.833333  55.333333     NaN     NaN  30.125000
std     16.140012   3.553168  27.622455     NaN     NaN  15.188694
min      2.000000   1.000000  21.000000     NaN     NaN  16.000000
25%      3.750000   3.000000  33.000000     NaN     NaN  21.750000
50%      5.000000   6.000000  50.000000     NaN     NaN  25.000000
75%      6.250000   9.000000  78.000000     NaN     NaN  32.500000
max     50.000000  11.000000  94.000000     NaN     NaN  56.000000

In [150]:
df[["Column1","Column2"]]

          Column1  Column2
Names
Ekrishna      1.0     78.0
Ram           2.0     94.0
Nishan        3.0     59.0
Sita          4.0     32.0
Bibek         6.0     94.0
Aarav         7.0     21.0
Ujjwal       11.0     33.0
Shyam         9.0     37.0
Puja          9.5     50.0
ABC           NaN      NaN

In [151]:
# Fancy Indexing => Allows accessing multiple indexes at once
import numpy as np
array = np.array([1,2,3,4,5])
# print(array[0])
# print(array[-1])
print(array[[0,-2,-1]])

[1 4 5]

In [152]:
df[['Column1',"Column2","Column5"]]

          Column1  Column2 Column5
Names
Ekrishna      1.0     78.0   False
Ram           2.0     94.0    True
Nishan        3.0     59.0    True
Sita          4.0     32.0   False
Bibek         6.0     94.0    True
Aarav         7.0     21.0   False
Ujjwal       11.0     33.0   False
Shyam         9.0     37.0   False
Puja          9.5     50.0    True
ABC           NaN      NaN    True

In [153]:
df.loc['Ujjwal', 'Column1'] = 10.0
df.loc['Ujjwal']

index        6.0
Column1     10.0
Column2     33.0
Column3        D
Column5    False
Age         26.0
Name: Ujjwal, dtype: object

In [154]:
df.loc['Sunita', 'Column1'] = 5.0

In [155]:
df.loc['ABC','Column1'] = 8.0

In [156]:
df

          index  Column1  Column2 Column3 Column5   Age
Names
Ekrishna    5.0      1.0     78.0       A   False  52.0
Ram        50.0      2.0     94.0       A    True  25.0
Nishan      2.0      3.0     59.0       B    True  16.0
Sita        3.0      4.0     32.0       C   False  18.0
Bibek       4.0      6.0     94.0       D    True  56.0
Aarav       5.0      7.0     21.0       A   False  23.0
Ujjwal      6.0     10.0     33.0       D   False  26.0
Shyam       7.0      9.0     37.0       D   False  25.0
Puja        NaN      9.5     50.0     NaN    True   NaN
ABC         NaN      8.0      NaN     NaN    True   NaN
Sunita      NaN      5.0      NaN     NaN     NaN   NaN

In [157]:
df[['Column1']]

          Column1
Names
Ekrishna      1.0
Ram           2.0
Nishan        3.0
Sita          4.0
Bibek         6.0
Aarav         7.0
Ujjwal       10.0
Shyam         9.0
Puja          9.5
ABC           8.0
Sunita        5.0

In [158]:
total_column1 = df[['Column1','Column2']].sum()
print("Total values of total_column1:", total_column1)
average_column1 = df[['Column1','Column2']].mean()
print("Average total_column1:", average_column1)
median_column1 = df['Column1'].median()
print("Median:", median_column1)
mode = df['Column1'].mode()[0]
print("Mode of Column1 of Employees:", mode)

Total values of total_column1: Column1     64.5
Column2    498.0
dtype: float64
Average total_column1: Column1     5.863636
Column2    55.333333
dtype: float64
Median: 6.0
Mode of Column1 of Employees: 1.0

| Use Case      | Use `.loc[]` when...                | Use `.iloc[]` when...                        |
| ------------- | ----------------------------------- | -------------------------------------------- |
| Column access | You know column names               | You know column positions                    |
| Indexing rows | You use custom labels (e.g., names) | You want rows by number (e.g., first 5 rows) |

In [159]:
print(df.iloc[-1]) # Selects the row at index position 1
print(df.iloc[1:3]) # Selects rows 1 and 2 (Python slicing is end-exclusive).
print(df.iloc[1:3,0:2]) # Selects rows 1 and 2 AND columns 0 and 1 (again, slice is end-exclusive)

index      NaN
Column1    5.0
Column2    NaN
Column3    NaN
Column5    NaN
Age        NaN
Name: Sunita, dtype: object
        index  Column1  Column2 Column3 Column5   Age
Names
Ram      50.0      2.0     94.0       A    True  25.0
Nishan    2.0      3.0     59.0       B    True  16.0
        index  Column1
Names
Ram      50.0      2.0
Nishan    2.0      3.0

In [ ]:
#checking null values
df.isnull().sum()
# df.isna().sum() - same

index      3
Column1    0
Column2    2
Column3    3
Column5    1
Age        3
dtype: int64

In [161]:
df

          index  Column1  Column2 Column3 Column5   Age
Names
Ekrishna    5.0      1.0     78.0       A   False  52.0
Ram        50.0      2.0     94.0       A    True  25.0
Nishan      2.0      3.0     59.0       B    True  16.0
Sita        3.0      4.0     32.0       C   False  18.0
Bibek       4.0      6.0     94.0       D    True  56.0
Aarav       5.0      7.0     21.0       A   False  23.0
Ujjwal      6.0     10.0     33.0       D   False  26.0
Shyam       7.0      9.0     37.0       D   False  25.0
Puja        NaN      9.5     50.0     NaN    True   NaN
ABC         NaN      8.0      NaN     NaN    True   NaN
Sunita      NaN      5.0      NaN     NaN     NaN   NaN

In [162]:
df.shape
df.loc['Def','Column1'] = 10
df

          index  Column1  Column2 Column3 Column5   Age
Names
Ekrishna    5.0      1.0     78.0       A   False  52.0
Ram        50.0      2.0     94.0       A    True  25.0
Nishan      2.0      3.0     59.0       B    True  16.0
Sita        3.0      4.0     32.0       C   False  18.0
Bibek       4.0      6.0     94.0       D    True  56.0
Aarav       5.0      7.0     21.0       A   False  23.0
Ujjwal      6.0     10.0     33.0       D   False  26.0
Shyam       7.0      9.0     37.0       D   False  25.0
Puja        NaN      9.5     50.0     NaN    True   NaN
ABC         NaN      8.0      NaN     NaN    True   NaN
Sunita      NaN      5.0      NaN     NaN     NaN   NaN
Def         NaN     10.0      NaN     NaN     NaN   NaN

In [163]:
row_def = df.iloc[-1]
row_def

index       NaN
Column1    10.0
Column2     NaN
Column3     NaN
Column5     NaN
Age         NaN
Name: Def, dtype: object

In [164]:
df.isna().sum()

index      4
Column1    0
Column2    3
Column3    4
Column5    2
Age        4
dtype: int64

In [165]:
df

          index  Column1  Column2 Column3 Column5   Age
Names
Ekrishna    5.0      1.0     78.0       A   False  52.0
Ram        50.0      2.0     94.0       A    True  25.0
Nishan      2.0      3.0     59.0       B    True  16.0
Sita        3.0      4.0     32.0       C   False  18.0
Bibek       4.0      6.0     94.0       D    True  56.0
Aarav       5.0      7.0     21.0       A   False  23.0
Ujjwal      6.0     10.0     33.0       D   False  26.0
Shyam       7.0      9.0     37.0       D   False  25.0
Puja        NaN      9.5     50.0     NaN    True   NaN
ABC         NaN      8.0      NaN     NaN    True   NaN
Sunita      NaN      5.0      NaN     NaN     NaN   NaN
Def         NaN     10.0      NaN     NaN     NaN   NaN

In [166]:
df = df.fillna(10)
df

          index  Column1  Column2 Column3 Column5   Age
Names
Ekrishna    5.0      1.0     78.0       A   False  52.0
Ram        50.0      2.0     94.0       A    True  25.0
Nishan      2.0      3.0     59.0       B    True  16.0
Sita        3.0      4.0     32.0       C   False  18.0
Bibek       4.0      6.0     94.0       D    True  56.0
Aarav       5.0      7.0     21.0       A   False  23.0
Ujjwal      6.0     10.0     33.0       D   False  26.0
Shyam       7.0      9.0     37.0       D   False  25.0
Puja       10.0      9.5     50.0      10    True  10.0
ABC        10.0      8.0     10.0      10    True  10.0
Sunita     10.0      5.0     10.0      10      10  10.0
Def        10.0     10.0     10.0      10      10  10.0

In [167]:
df.shape

(12, 6)

In [168]:
df.isnull().sum()

index      0
Column1    0
Column2    0
Column3    0
Column5    0
Age        0
dtype: int64

In [169]:
import numpy as np
df.loc['Ujjwal','Column5'] = np.nan

In [170]:
df

          index  Column1  Column2 Column3 Column5   Age
Names
Ekrishna    5.0      1.0     78.0       A   False  52.0
Ram        50.0      2.0     94.0       A    True  25.0
Nishan      2.0      3.0     59.0       B    True  16.0
Sita        3.0      4.0     32.0       C   False  18.0
Bibek       4.0      6.0     94.0       D    True  56.0
Aarav       5.0      7.0     21.0       A   False  23.0
Ujjwal      6.0     10.0     33.0       D     NaN  26.0
Shyam       7.0      9.0     37.0       D   False  25.0
Puja       10.0      9.5     50.0      10    True  10.0
ABC        10.0      8.0     10.0      10    True  10.0
Sunita     10.0      5.0     10.0      10      10  10.0
Def        10.0     10.0     10.0      10      10  10.0

In [171]:
df.isnull().sum()

index      0
Column1    0
Column2    0
Column3    0
Column5    1
Age        0
dtype: int64

In [172]:
df

          index  Column1  Column2 Column3 Column5   Age
Names
Ekrishna    5.0      1.0     78.0       A   False  52.0
Ram        50.0      2.0     94.0       A    True  25.0
Nishan      2.0      3.0     59.0       B    True  16.0
Sita        3.0      4.0     32.0       C   False  18.0
Bibek       4.0      6.0     94.0       D    True  56.0
Aarav       5.0      7.0     21.0       A   False  23.0
Ujjwal      6.0     10.0     33.0       D     NaN  26.0
Shyam       7.0      9.0     37.0       D   False  25.0
Puja       10.0      9.5     50.0      10    True  10.0
ABC        10.0      8.0     10.0      10    True  10.0
Sunita     10.0      5.0     10.0      10      10  10.0
Def        10.0     10.0     10.0      10      10  10.0

In [173]:
df.dropna(axis=0, inplace=True,how='any') # To drop columns with null values
df

          index  Column1  Column2 Column3 Column5   Age
Names
Ekrishna    5.0      1.0     78.0       A   False  52.0
Ram        50.0      2.0     94.0       A    True  25.0
Nishan      2.0      3.0     59.0       B    True  16.0
Sita        3.0      4.0     32.0       C   False  18.0
Bibek       4.0      6.0     94.0       D    True  56.0
Aarav       5.0      7.0     21.0       A   False  23.0
Shyam       7.0      9.0     37.0       D   False  25.0
Puja       10.0      9.5     50.0      10    True  10.0
ABC        10.0      8.0     10.0      10    True  10.0
Sunita     10.0      5.0     10.0      10      10  10.0
Def        10.0     10.0     10.0      10      10  10.0

In [174]:
df.iloc[0,0] = np.nan
df

          index  Column1  Column2 Column3 Column5   Age
Names
Ekrishna    NaN      1.0     78.0       A   False  52.0
Ram        50.0      2.0     94.0       A    True  25.0
Nishan      2.0      3.0     59.0       B    True  16.0
Sita        3.0      4.0     32.0       C   False  18.0
Bibek       4.0      6.0     94.0       D    True  56.0
Aarav       5.0      7.0     21.0       A   False  23.0
Shyam       7.0      9.0     37.0       D   False  25.0
Puja       10.0      9.5     50.0      10    True  10.0
ABC        10.0      8.0     10.0      10    True  10.0
Sunita     10.0      5.0     10.0      10      10  10.0
Def        10.0     10.0     10.0      10      10  10.0

In [175]:
df.dropna(axis = 0, inplace=True) # To drop rows with null values
df

        index  Column1  Column2 Column3 Column5   Age
Names
Ram      50.0      2.0     94.0       A    True  25.0
Nishan    2.0      3.0     59.0       B    True  16.0
Sita      3.0      4.0     32.0       C   False  18.0
Bibek     4.0      6.0     94.0       D    True  56.0
Aarav     5.0      7.0     21.0       A   False  23.0
Shyam     7.0      9.0     37.0       D   False  25.0
Puja     10.0      9.5     50.0      10    True  10.0
ABC      10.0      8.0     10.0      10    True  10.0
Sunita   10.0      5.0     10.0      10      10  10.0
Def      10.0     10.0     10.0      10      10  10.0

In [176]:
df.isnull().sum()

index      0
Column1    0
Column2    0
Column3    0
Column5    0
Age        0
dtype: int64

In [177]:
df

        index  Column1  Column2 Column3 Column5   Age
Names
Ram      50.0      2.0     94.0       A    True  25.0
Nishan    2.0      3.0     59.0       B    True  16.0
Sita      3.0      4.0     32.0       C   False  18.0
Bibek     4.0      6.0     94.0       D    True  56.0
Aarav     5.0      7.0     21.0       A   False  23.0
Shyam     7.0      9.0     37.0       D   False  25.0
Puja     10.0      9.5     50.0      10    True  10.0
ABC      10.0      8.0     10.0      10    True  10.0
Sunita   10.0      5.0     10.0      10      10  10.0
Def      10.0     10.0     10.0      10      10  10.0

In [178]:
df.iloc[0,2] = np.nan
df

        index  Column1  Column2 Column3 Column5   Age
Names
Ram      50.0      2.0      NaN       A    True  25.0
Nishan    2.0      3.0     59.0       B    True  16.0
Sita      3.0      4.0     32.0       C   False  18.0
Bibek     4.0      6.0     94.0       D    True  56.0
Aarav     5.0      7.0     21.0       A   False  23.0
Shyam     7.0      9.0     37.0       D   False  25.0
Puja     10.0      9.5     50.0      10    True  10.0
ABC      10.0      8.0     10.0      10    True  10.0
Sunita   10.0      5.0     10.0      10      10  10.0
Def      10.0     10.0     10.0      10      10  10.0

In [179]:
df.isnull().sum()

index      0
Column1    0
Column2    1
Column3    0
Column5    0
Age        0
dtype: int64

In [180]:
df = df.fillna("A")

In [181]:
df

        index  Column1 Column2 Column3 Column5   Age
Names
Ram      50.0      2.0       A       A    True  25.0
Nishan    2.0      3.0    59.0       B    True  16.0
Sita      3.0      4.0    32.0       C   False  18.0
Bibek     4.0      6.0    94.0       D    True  56.0
Aarav     5.0      7.0    21.0       A   False  23.0
Shyam     7.0      9.0    37.0       D   False  25.0
Puja     10.0      9.5    50.0      10    True  10.0
ABC      10.0      8.0    10.0      10    True  10.0
Sunita   10.0      5.0    10.0      10      10  10.0
Def      10.0     10.0    10.0      10      10  10.0

-----------------------------------Pandas Pivot-------------------
=========================The pivot() function in Pandas reshapes data based on column values. It takes simple column-wise data as input, and groups the entries into a two-dimensional table.

===============================================================
![alt text](image.png)

---------------------------------------------------------

a Pivot is used to reshape data — it transforms unique values from one column into new columns, and uses another column’s values to fill in the cells.

Syntax: 
df.pivot(index='row_column', columns='column_column', values='values_column')

Pivot Table

Can handle duplicates by applying an aggregation function (mean, sum, etc.)

Syntax:
pd.pivot_table(data, index="", columns="", values="", aggfunc="")

pivot_df = pd.pivot_table(

)

print(pivot_df)

In [182]:
df

        index  Column1 Column2 Column3 Column5   Age
Names
Ram      50.0      2.0       A       A    True  25.0
Nishan    2.0      3.0    59.0       B    True  16.0
Sita      3.0      4.0    32.0       C   False  18.0
Bibek     4.0      6.0    94.0       D    True  56.0
Aarav     5.0      7.0    21.0       A   False  23.0
Shyam     7.0      9.0    37.0       D   False  25.0
Puja     10.0      9.5    50.0      10    True  10.0
ABC      10.0      8.0    10.0      10    True  10.0
Sunita   10.0      5.0    10.0      10      10  10.0
Def      10.0     10.0    10.0      10      10  10.0

In [183]:
import pandas as pd
df2 = pd.read_csv("sampledata.csv")
df2

   Column1  Column2 Column3  Column4  Column5
0        1       78       A    -0.61    False
1        2       94       C    -0.90     True
2        3       59       B    -0.17     True
3        4       32       C    -2.74    False
4        5       65       B     1.14     True
5        6       94       D    -0.76     True
6        7       21       A    -1.48    False
7        8       74       D    -0.37     True
8        9       37       D     1.00    False
9       10       27       A    -0.27     True

In [184]:

df

        index  Column1 Column2 Column3 Column5   Age
Names
Ram      50.0      2.0       A       A    True  25.0
Nishan    2.0      3.0    59.0       B    True  16.0
Sita      3.0      4.0    32.0       C   False  18.0
Bibek     4.0      6.0    94.0       D    True  56.0
Aarav     5.0      7.0    21.0       A   False  23.0
Shyam     7.0      9.0    37.0       D   False  25.0
Puja     10.0      9.5    50.0      10    True  10.0
ABC      10.0      8.0    10.0      10    True  10.0
Sunita   10.0      5.0    10.0      10      10  10.0
Def      10.0     10.0    10.0      10      10  10.0

In [185]:
df2 = df
df2

        index  Column1 Column2 Column3 Column5   Age
Names
Ram      50.0      2.0       A       A    True  25.0
Nishan    2.0      3.0    59.0       B    True  16.0
Sita      3.0      4.0    32.0       C   False  18.0
Bibek     4.0      6.0    94.0       D    True  56.0
Aarav     5.0      7.0    21.0       A   False  23.0
Shyam     7.0      9.0    37.0       D   False  25.0
Puja     10.0      9.5    50.0      10    True  10.0
ABC      10.0      8.0    10.0      10    True  10.0
Sunita   10.0      5.0    10.0      10      10  10.0
Def      10.0     10.0    10.0      10      10  10.0

In [186]:
df2

        index  Column1 Column2 Column3 Column5   Age
Names
Ram      50.0      2.0       A       A    True  25.0
Nishan    2.0      3.0    59.0       B    True  16.0
Sita      3.0      4.0    32.0       C   False  18.0
Bibek     4.0      6.0    94.0       D    True  56.0
Aarav     5.0      7.0    21.0       A   False  23.0
Shyam     7.0      9.0    37.0       D   False  25.0
Puja     10.0      9.5    50.0      10    True  10.0
ABC      10.0      8.0    10.0      10    True  10.0
Sunita   10.0      5.0    10.0      10      10  10.0
Def      10.0     10.0    10.0      10      10  10.0

In [187]:
df2.iloc[6,2]="B"
df2

        index  Column1 Column2 Column3 Column5   Age
Names
Ram      50.0      2.0       A       A    True  25.0
Nishan    2.0      3.0    59.0       B    True  16.0
Sita      3.0      4.0    32.0       C   False  18.0
Bibek     4.0      6.0    94.0       D    True  56.0
Aarav     5.0      7.0    21.0       A   False  23.0
Shyam     7.0      9.0    37.0       D   False  25.0
Puja     10.0      9.5       B      10    True  10.0
ABC      10.0      8.0    10.0      10    True  10.0
Sunita   10.0      5.0    10.0      10      10  10.0
Def      10.0     10.0    10.0      10      10  10.0

In [188]:
df2 = df2.drop([4,7])
df2

KeyError: '[4, 7] not found in axis'

In [ ]:
df2

In [ ]:
df2.pivot(index='Column3', columns='Column5', values='Column2')

In [ ]:
df2.iloc[-1,-1] = False
df2

In [ ]:
df2.pivot_table(index='Column3', columns='Column5', values='Column2', aggfunc='count')

In [ ]:
# pd.pivot(data=df2, index='Column3', columns='Column5', values='Column4')
pd.pivot_table(data=df2, index='Column3', columns='Column5', values='Column4', aggfunc='count')

In [ ]:
df2.iloc[3,4] = True
df2

In [ ]:
# df2.set_index('Column3', inplace=True)
df2.reset_index(inplace=True)
df2

In [ ]:

df2.columns
df2.iloc[1,1] = 4
df2

In [ ]:
df2

In [ ]:
df2.reset_index(inplace=True)
df2

In [ ]:
df2.drop(columns=['index'], inplace=True)
df2

In [ ]:
df2.iloc[3,0] = True
df2

In [ ]:
pivot = df2.pivot_table(index='Column3', columns='Column5', values='Column1', aggfunc =['mean','median'])
pivot

In [ ]:
df2.iloc[3,2] = 'C'
df2

In [ ]:
df2 = pd.read_csv("sampledata.csv")
df_pivot = pd.pivot_table(
    data = df2, index='Column5', columns='Column3', values = 'Column1', aggfunc=['mean', 'median']
)
df_pivot

In [ ]:
# Update Ram's Column2
df.loc['Ram', 'Column2'] = 100

# Recreate the pivot table after update
df_pivot = pd.pivot_table(
    data=df,
    index='Names',
    values='Column2',
    aggfunc='sum'
)

print(df_pivot.loc["Ram"])  # Should now show 100000

| Function        | What it does                                                                         |
| --------------- | ------------------------------------------------------------------------------------ |
| `pivot()`       | Just reshapes data; must be unique for index+columns; no aggregation                 |
| `pivot_table()` | Reshapes data **and** can aggregate duplicates using `aggfunc` (`sum`, `mean`, etc.) |

============================= DataFrame.dropna() function

this is a dropna() functions:
---------------DataFrame.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)



axis: It determines the axis to remove. Set it to 1 or column to remove columns containing missing values. By default, it removes rows with NA from DataFrame.
how: It takes the following inputs:
‘any’: This is the default case to drop the column if it has at least one value missing.
‘all’: Drop the column only if it has all the values as NA.
thresh: It applies a condition to drop the columns only if it does not contain the required number of values. It takes an int as input.
subset: While dropping columns, it is used to specify the list of rows to be considered to find NA.
inplace: It is used to specify whether to return a new DataFrame or update an existing one. It is a boolean flag with default False.

![alt text](image-1.png)

In [ ]:
import numpy as np
import pandas as pd
data = {
    "Name": ["Joe","Sam","Harry"],
    "Age":[20,np.nan,19],
    "Marks":[85.10, 95.65, np.nan]
} 
df = pd.DataFrame(data)
df

In [ ]:
df.dropna(subset='Age')

In [ ]:
data = {
    "name" : ["Joe","Sam","Harry", "Ujjwal"],
    "Age":[20,np.nan,19, np.nan],
    "Marks":[85.10, 95.65, np.nan, np.nan]
}

df = pd.DataFrame(data)
df

In [ ]:
df.isnull().sum()

In [ ]:
df.dropna(how='all', axis=1)

In [ ]:
import pandas as pd
import numpy as np

# Sample data
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, np.nan, 30],
    'Salary': [50000, 60000, np.nan]
})
print(df)
# Drop rows where 'Age' or 'Salary' is missing
clean_df = df.dropna(axis=1, subset=[0,1], how='any')
print(clean_df)

In [ ]:
import pandas as pd
df_nan = pd.read_csv("dropna_nan.csv")
df_nan

In [ ]:
df_nan[['Age','Name','Score']]

In [ ]:
df_nan.drop(columns=['Name'], inplace=True)
df_nan

In [ ]:
df_nan["Age"].median(), df_nan["Score"].median()

In [ ]:
df_nan.median()

In [ ]:
df_nan.fillna(df_nan.median())

In [ ]:
df_nan

In [ ]:
df_nan1 = pd.DataFrame(df_nan['Age'].fillna(20))
df_nan1

In [ ]:
df_nan2 = pd.DataFrame(df_nan['Score'].fillna(df_nan['Score'].mean()))

In [ ]:
df_nan2

In [ ]:
df_nan1

In [ ]:
df_nan2

In [ ]:
df = pd.concat((df_nan1, df_nan2), axis=1)
df

In [ ]:
df_nan['Score'].mean()

In [ ]:
df_nan['Score'].fillna(df_nan['Score'].mean())

In [ ]:
df_nan['Score'].mean()

In [ ]:
df_nan['Score'].fillna(df_nan['Score'].mean())

In [ ]:
df_clean

In [ ]:
df_nan

In [ ]:
df_clean = df_nan.dropna(axis=1)
df_clean

In [ ]:
df_nan

In [ ]:
df_age_clean = df_nan.dropna(axis=0)
df_age_clean

In [ ]:
df_nan

In [ ]:
df_nan

In [ ]:
import numpy as np
# df_rep = df_nan.replace(np.nan, 25.0)
df_rep = df_nan.replace(np.nan, 25.0)
df_rep

In [ ]:
df_rep = df_rep.replace(0, 15)
df_rep

In [ ]:
# df_age_clean = df_age_clean.fillna(df_age_clean["Age"].mean())
# df_age_clean

| Parameter   | Description                                                                                                                                                          | Example / Notes                                                                                                                  |
| ----------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------- |
| **axis**    | Determines if you drop **rows** or **columns** with missing values. `0` = rows, `1` = columns                                                                        | `df.dropna(axis=0)` → drop rows with NaN<br>`df.dropna(axis=1)` → drop columns with NaN                                          |
| **how**     | Determines if a row/column is dropped **when it has any or all NaNs**. Options:<br>`any` → drop if **any NaN** exists<br>`all` → drop only if **all values are NaN** | `df.dropna(how='any')` → default, drops rows with any missing value<br>`df.dropna(how='all')` → only drops rows completely empty |
| **thresh**  | Minimum number of **non-NaN values required to keep** the row/column                                                                                                 | `df.dropna(thresh=2)` → keep rows with **at least 2 non-NaN values**                                                             |
| **subset**  | Only consider certain columns for checking NaN                                                                                                                       | `df.dropna(subset=['Age', 'Score'])` → only check these columns                                                                  |
| **inplace** | If `True`, modifies the original DataFrame. If `False` (default), returns a new DataFrame                                                                            | `df.dropna(inplace=True)` → original `df` is updated<br>`df_clean = df.dropna()` → creates new cleaned df                        |

In [ ]:
import pandas as pd
data = {
    "Name": ["Alice", "Bob", "Charlie","Alice", "Bob", "Charlie","Alice","Bob","Charlie", "Alice"],
    "Subjects": ["Math", "Math", "Math","Science", "Science", "Science","English","English","English", "Math"],
    "Scores": [85, 90, 78, 88, 92, 80, 97, 86, 89,85]
}
df = pd.DataFrame(data)
df

In [ ]:
# Since pivot cannot handle duplicates, 
# We need to use pivot_table for handling the duplicates
df.pivot_table(index="Name", columns="Subjects", values="Scores", aggfunc='mean')

In [ ]:
df.duplicated().sum()

In [ ]:
df.drop_duplicates(inplace=True)
df

In [ ]:
df.duplicated().sum()

In [ ]:
import pandas as pd

students = {
    "id" : [1,2,3,4,5,6],
    "Name": ["Alice", "Bob", "Charlie","David", "Eva", "Frank"],
    "Age": [20, 21, 19, 22, 20, 23],
}

marks = {
    "id" : [1,2,3,4,5,6],
    # "student_id": [1,2,3,10,11,12],
    "Name": ["Alice", "Bob", "Charlie","Ujjwal", "Ram", "Sita"],
    "Math": [85, 90, 78, 88, 92, 80],
    "Science": [88, 92, 80, 85, 87, 90],
    "English": [97, 86, 89, 91, 93, 88]
}

students = pd.DataFrame(students)
marks = pd.DataFrame(marks)
print(students)
print(marks)
print()
print()

merged = pd.merge(students, marks, on="Name", how="right")
# # merged = pd.merge(students, marks, , how="outer")
print(merged)

In [ ]:
concatenated = pd.concat([students, marks], axis=0)
print(concatenated)

In [ ]:
concatenated.replace(np.nan,"ujjwal", inplace=True)

In [ ]:
concatenated.replace("ujjwal", "Ujjwal")

In [ ]:
concatenated = pd.concat([students, marks], axis=1)
print(concatenated)