Load the dataset

In [24]:
import pandas as pd
df = pd.read_csv("blood_type_distribution.csv")
df

,Country,Population,O+,A+,B+,AB+,O-,A-,B-,AB-,Continent
0,Albania,3107100,34.10,31.20,14.50,5.20,6.00,5.50,2.60,0.90,EU
1,Algeria,47022473,40.00,30.00,15.00,4.25,6.60,2.30,1.10,0.75,AF
2,Argentina,46994384,50.34,31.09,8.20,2.16,4.29,2.98,0.74,0.20,SA
3,Armenia,2976765,29.00,46.30,12.00,5.60,2.00,3.70,1.00,0.40,AS
4,Australia,26768598,38.00,32.00,12.00,4.00,7.00,6.00,2.00,1.00,OC
...,...,...,...,...,...,...,...,...,...,...,...
122,Venezuela,31250306,58.30,28.20,5.60,1.90,4.00,1.50,0.40,0.10,SA
123,Vietnam,105758975,41.70,20.90,30.80,4.98,0.30,0.10,0.20,0.02,AS
124,Yemen,32140443,47.84,27.50,15.32,2.14,3.66,2.10,1.17,0.16,AS
125,Zimbabwe,17150352,45.70,28.80,18.00,4.10,1.70,1.00,0.40,0.30,AF
126,World,8057236243,38.40,27.30,8.10,2.00,13.10,8.10,2.00,0.01,NaN

In [25]:
df.head()

,Country,Population,O+,A+,B+,AB+,O-,A-,B-,AB-,Continent
0,Albania,3107100,34.10,31.20,14.5,5.20,6.00,5.50,2.60,0.90,EU
1,Algeria,47022473,40.00,30.00,15.0,4.25,6.60,2.30,1.10,0.75,AF
2,Argentina,46994384,50.34,31.09,8.2,2.16,4.29,2.98,0.74,0.20,SA
3,Armenia,2976765,29.00,46.30,12.0,5.60,2.00,3.70,1.00,0.40,AS
4,Australia,26768598,38.00,32.00,12.0,4.00,7.00,6.00,2.00,1.00,OC

In [27]:
df.shape

(127, 11)

In [28]:
df.columns

Index(['Country', 'Population', 'O+', 'A+', 'B+', 'AB+', 'O-', 'A-', 'B-',
       'AB-', 'Continent'],
      dtype='str')

In [29]:
df.dtypes

Country           str
Population      int64
O+            float64
A+            float64
B+            float64
AB+           float64
O-            float64
A-            float64
B-            float64
AB-           float64
Continent         str
dtype: object

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 127 entries, 0 to 126
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Country     127 non-null    str
 1   Population  127 non-null    int64
 2   O+          127 non-null    float64
 3   A+          127 non-null    float64
 4   B+          127 non-null    float64
 5   AB+         127 non-null    float64
 6   O-          126 non-null    float64
 7   A-          126 non-null    float64
 8   B-          126 non-null    float64
 9   AB-         124 non-null    float64
 10  Continent   116 non-null    str
dtypes: float64(8), int64(1), str(2)
memory usage: 12.3 KB

In [31]:
df.describe()

,Population,O+,A+,B+,AB+,O-,A-,B-,AB-
count,1.270000e+02,127.000000,127.000000,127.000000,127.000000,126.000000,126.000000,126.000000,124.000000
mean,1.226677e+08,40.424331,29.153622,16.287480,4.679921,4.126349,3.362619,1.360397,0.473710
std,7.324852e+08,9.874698,6.587261,7.510459,2.258816,2.669749,2.582812,0.867657,0.377158
min,4.027200e+04,27.000000,14.000000,4.720000,0.500000,0.060000,0.010000,0.010000,0.010000
25%,5.536691e+06,32.780000,24.130000,10.000000,2.850000,1.850000,1.000000,0.602500,0.130000
50%,1.301727e+07,38.000000,30.000000,15.000000,4.250000,4.295000,2.715000,1.300000,0.400000
75%,4.715145e+07,46.750000,34.000000,21.030000,6.300000,6.000000,6.000000,2.000000,0.900000
max,8.057236e+09,75.000000,46.300000,36.800000,11.320000,13.300000,9.000000,3.130000,1.200000

In [32]:
df.isnull().sum()

Country        0
Population     0
O+             0
A+             0
B+             0
AB+            0
O-             1
A-             1
B-             1
AB-            3
Continent     11
dtype: int64

In [37]:
df.isnull().sum().idxmax()

'Continent'

From your blood-type dataset, display only the Country column.

In [38]:
df['Country']

0        Albania
1        Algeria
2      Argentina
3        Armenia
4      Australia
         ...
122    Venezuela
123      Vietnam
124        Yemen
125     Zimbabwe
126        World
Name: Country, Length: 127, dtype: str

Display these 3 columns together:

Country
Population
Continent

In [40]:
df[['Country', 'Population', 'Continent']]

       Country  Population Continent
0      Albania     3107100        EU
1      Algeria    47022473        AF
2    Argentina    46994384        SA
3      Armenia     2976765        AS
4    Australia    26768598        OC
..         ...         ...       ...
122  Venezuela    31250306        SA
123    Vietnam   105758975        AS
124      Yemen    32140443        AS
125   Zimbabwe    17150352        AF
126      World  8057236243       NaN

[127 rows x 3 columns]

Using iloc, display the first 5 rows of the dataset.

In [43]:
df.iloc[:5]

,Country,Population,O+,A+,B+,AB+,O-,A-,B-,AB-,Continent
0,Albania,3107100,34.10,31.20,14.5,5.20,6.00,5.50,2.60,0.90,EU
1,Algeria,47022473,40.00,30.00,15.0,4.25,6.60,2.30,1.10,0.75,AF
2,Argentina,46994384,50.34,31.09,8.2,2.16,4.29,2.98,0.74,0.20,SA
3,Armenia,2976765,29.00,46.30,12.0,5.60,2.00,3.70,1.00,0.40,AS
4,Australia,26768598,38.00,32.00,12.0,4.00,7.00,6.00,2.00,1.00,OC

Using loc, select the first country/first row of your dataset.

In [46]:
df.loc[0, 'Country']

'Albania'

Using your dataset, show only the countries from Asia.

In [47]:
df[df['Continent'] == 'AS']

,Country,Population,O+,A+,B+,AB+,O-,A-,B-,AB-,Continent
3,Armenia,2976765,29.00,46.30,12.00,5.60,2.00,3.70,1.00,0.40,AS
6,Azerbaijan,10650239,29.80,30.00,21.10,9.00,3.30,3.40,2.40,1.00,AS
7,Bahrain,1566888,48.48,15.35,22.61,3.67,3.27,1.33,1.04,0.25,AS
8,Bangladesh,168697184,29.21,26.30,33.12,9.59,0.53,0.48,0.60,0.17,AS
11,Bhutan,884546,38.15,29.45,23.86,8.41,0.06,0.04,0.04,0.01,AS
17,Cambodia,17063669,46.70,27.20,18.50,4.90,1.30,0.80,0.50,0.10,AS
25,Cyprus,1320525,35.22,40.35,11.11,4.72,3.85,3.48,0.87,0.40,AS
39,Georgia,4900961,34.80,32.30,11.90,6.00,6.20,5.70,2.10,0.50,AS
45,Hong Kong,7297821,42.80,25.50,25.80,5.90,0.70,0.10,0.20,0.10,AS
48,India,1409128296,32.53,21.80,32.10,7.70,2.03,1.36,2.00,0.48,AS
49,Indonesia,281562465,36.82,25.87,28.85,7.96,0.18,0.13,0.15,0.04,AS
50,Iran,88386937,36.50,27.00,22.20,4.00,5.00,2.00,2.50,0.80,AS
51,Iraq,42083436,32.10,25.00,25.60,7.40,3.60,2.70,2.70,0.90,AS
53,Israel,9402617,32.00,34.00,17.00,7.00,3.00,4.00,2.00,1.00,AS
57,Japan,123201945,29.90,39.80,19.90,9.90,0.15,0.20,0.10,0.05,AS
58,Jordan,11174024,33.03,32.86,16.56,6.28,4.40,3.97,2.06,0.04,AS
59,Kazakhstan,20260006,30.70,29.80,24.20,8.30,2.30,2.20,1.80,0.40,AS
61,Laos,7953556,37.52,19.73,35.36,6.85,0.20,0.10,0.20,0.05,AS
63,Lebanon,5364482,38.40,32.30,9.50,3.20,7.70,6.50,1.70,0.70,AS
68,Macao,644426,41.50,26.10,25.40,6.30,0.33,0.09,0.17,0.05,AS
69,Malaysia,34564810,34.32,30.35,27.37,7.46,0.17,0.15,0.14,0.04,AS
75,Mongolia,3281676,36.40,29.20,8.10,7.89,13.30,8.00,2.00,0.01,AS
77,Myanmar,57527139,35.70,23.80,32.70,6.95,0.30,0.20,0.30,0.05,AS
79,Nepal,31122387,35.20,36.30,27.10,2.60,0.30,0.20,0.20,0.10,AS
84,North Korea,26298666,27.15,31.08,30.15,11.32,0.08,0.10,0.10,0.03,AS
87,Oman,3901992,44.90,17.40,20.20,6.80,7.40,0.60,2.70,NaN,AS
88,Pakistan,252363571,30.04,21.53,30.24,8.83,3.10,2.22,3.13,0.91,AS
92,Philippines,118277063,45.90,22.90,24.90,5.97,0.10,0.10,0.10,0.03,AS
95,People's Republic of China,1416043270,34.00,27.60,28.90,8.40,0.40,0.25,0.20,0.15,AS
98,Saudi Arabia,36544431,47.80,16.00,17.90,4.00,4.00,2.00,1.00,0.30,AS
100,Singapore,6028459,44.70,23.90,24.50,5.60,0.60,0.30,0.30,0.10,AS
105,South Korea,52081799,29.00,32.00,31.00,8.00,0.19,0.10,0.10,0.01,AS
107,Sri Lanka,21982608,43.42,21.00,25.78,5.13,2.12,1.04,1.25,0.26,AS
111,Syria,23865423,43.00,30.00,14.00,3.70,5.00,3.00,1.00,0.30,AS
112,Taiwan,23595274,43.90,25.90,23.90,6.00,0.28,0.01,0.01,0.01,AS
113,Thailand,69920998,40.80,16.90,36.80,4.97,0.20,0.10,0.20,0.03,AS
115,Turkey,84119531,29.40,38.30,13.20,6.40,4.40,5.50,2.10,0.70,AS
118,United Arab Emirates,10032213,44.10,21.90,20.90,4.30,4.30,2.10,2.00,0.40,AS
121,Uzbekistan,36520593,29.42,30.93,24.98,9.27,1.68,1.77,1.42,0.53,AS
123,Vietnam,105758975,41.70,20.90,30.80,4.98,0.30,0.10,0.20,0.02,AS
124,Yemen,32140443,47.84,27.50,15.32,2.14,3.66,2.10,1.17,0.16,AS

Find all countries where O+ is greater than 40%.

In [48]:
df[df['O+'] > 40]

,Country,Population,O+,A+,B+,AB+,O-,A-,B-,AB-,Continent
2,Argentina,46994384,50.34,31.09,8.20,2.16,4.29,2.98,0.74,0.20,SA
7,Bahrain,1566888,48.48,15.35,22.61,3.67,3.27,1.33,1.04,0.25,AS
12,Bolivia,12311974,51.53,20.45,10.11,1.15,4.39,2.73,0.54,0.10,SA
17,Cambodia,17063669,46.70,27.20,18.50,4.90,1.30,0.80,0.50,0.10,AS
18,Cameroon,30966105,46.83,24.15,21.06,4.29,1.79,0.92,0.80,0.16,AF
20,Chile,18664652,55.01,28.08,8.02,1.81,4.19,2.14,0.61,0.14,SA
21,Colombia,49588357,61.30,21.11,7.28,1.47,5.13,2.70,0.70,0.31,SA
22,Costa Rica,5265575,49.70,28.50,12.40,3.00,3.40,1.90,0.90,0.20,NaN
24,Cuba,10966038,45.80,33.50,10.20,2.90,3.60,2.80,1.00,0.20,NaN
27,Democratic Republic of the Congo,115403027,59.50,21.30,15.20,2.40,1.00,0.30,0.20,0.10,AF
29,Dominican Republic,10815857,47.20,26.40,16.90,2.10,3.70,2.10,1.40,0.20,NaN
30,Ecuador,18309984,75.00,14.00,7.10,0.50,2.38,0.70,0.30,0.02,SA
32,El Salvador,6628702,62.00,23.00,11.00,1.00,1.00,1.00,0.70,0.30,NaN
35,Fiji,951611,43.00,33.30,16.50,4.80,1.00,0.70,0.50,0.20,OC
38,Gabon,2455105,57.55,20.52,17.19,2.54,1.35,0.48,0.41,0.06,AF
41,Ghana,34589092,53.80,17.60,18.30,2.80,4.50,1.30,1.30,0.20,AF
43,Guinea,13986179,46.88,21.64,22.86,4.52,2.00,0.90,1.00,0.20,AF
44,Honduras,9529188,57.50,25.00,7.80,2.50,2.70,1.70,0.60,0.20,NaN
45,Hong Kong,7297821,42.80,25.50,25.80,5.90,0.70,0.10,0.20,0.10,AS
47,Iceland,364036,46.80,27.20,9.00,2.00,8.20,4.80,1.60,0.40,EU
52,Ireland,5233461,47.00,26.00,9.00,2.00,8.00,5.00,2.00,1.00,EU
55,Ivory Coast,29981758,47.24,20.19,21.70,3.82,3.73,1.54,1.48,0.30,AF
56,Jamaica,2823713,51.10,20.00,20.00,1.90,3.50,2.00,1.00,0.50,NaN
60,Kenya,58246378,45.60,25.20,21.28,4.20,1.80,1.00,0.90,0.02,AF
64,Libya,7361263,42.64,20.86,11.19,4.50,7.26,3.24,1.64,0.67,AF
68,Macao,644426,41.50,26.10,25.40,6.30,0.33,0.09,0.17,0.05,AS
71,Mauritania,4328040,46.30,26.68,17.47,3.85,2.80,1.60,1.10,0.20,AF
73,Mexico,130739927,59.09,26.23,8.53,1.73,2.73,1.21,0.40,0.08,NaN
76,Morocco,37387585,42.30,30.80,14.00,4.00,4.50,3.10,1.50,0.40,AF
78,Namibia,2803660,50.58,20.49,20.21,1.02,4.22,1.71,1.69,0.08,AF
82,Nicaragua,6676948,62.00,20.00,11.00,4.00,1.00,1.00,0.70,0.30,NaN
83,Nigeria,236747130,50.23,21.61,19.59,3.47,2.70,1.16,1.05,0.19,AF
87,Oman,3901992,44.90,17.40,20.20,6.80,7.40,0.60,2.70,NaN,AS
89,Papua New Guinea,10046233,55.70,32.20,9.60,2.10,1.80,0.50,0.20,0.10,OC
90,Paraguay,7522549,63.07,21.32,4.72,1.38,5.89,2.97,0.49,0.15,SA
91,Peru,32600249,70.00,18.40,7.80,1.60,1.40,0.50,0.28,0.02,SA
92,Philippines,118277063,45.90,22.90,24.90,5.97,0.10,0.10,0.10,0.03,AS
98,Saudi Arabia,36544431,47.80,16.00,17.90,4.00,4.00,2.00,1.00,0.30,AS
100,Singapore,6028459,44.70,23.90,24.50,5.60,0.60,0.30,0.30,0.10,AS
103,Somalia,13017273,52.80,19.36,12.32,3.52,7.20,2.64,1.68,0.48,AF
107,Sri Lanka,21982608,43.42,21.00,25.78,5.13,2.12,1.04,1.25,0.26,AS
108,Sudan,50467278,48.00,27.70,15.20,2.30,3.50,1.80,0.80,0.20,AF
111,Syria,23865423,43.00,30.00,14.00,3.70,5.00,3.00,1.00,0.30,AS
112,Taiwan,23595274,43.90,25.90,23.90,6.00,0.28,0.01,0.01,0.01,AS
113,Thailand,69920998,40.80,16.90,36.80,4.97,0.20,0.10,0.20,0.03,AS
114,Tunisia,12048847,41.86,28.21,16.38,4.55,4.14,2.79,1.62,0.45,AF
116,Uganda,49283041,49.29,24.11,20.29,4.41,1.01,0.49,0.41,0.09,AF
118,United Arab Emirates,10032213,44.10,21.90,20.90,4.30,4.30,2.10,2.00,0.40,AS
122,Venezuela,31250306,58.30,28.20,5.60,1.90,4.00,1.50,0.40,0.10,SA
123,Vietnam,105758975,41.70,20.90,30.80,4.98,0.30,0.10,0.20,0.02,AS
124,Yemen,32140443,47.84,27.50,15.32,2.14,3.66,2.10,1.17,0.16,AS
125,Zimbabwe,17150352,45.70,28.80,18.00,4.10,1.70,1.00,0.40,0.30,AF

Find all countries where A+ is greater than 30%.

In [49]:
df[df['A+'] > 30]

,Country,Population,O+,A+,B+,AB+,O-,A-,B-,AB-,Continent
0,Albania,3107100,34.10,31.20,14.50,5.20,6.00,5.50,2.60,0.90,EU
2,Argentina,46994384,50.34,31.09,8.20,2.16,4.29,2.98,0.74,0.20,SA
3,Armenia,2976765,29.00,46.30,12.00,5.60,2.00,3.70,1.00,0.40,AS
4,Australia,26768598,38.00,32.00,12.00,4.00,7.00,6.00,2.00,1.00,OC
5,Austria,8967982,30.00,37.00,12.00,5.00,6.00,7.00,2.00,0.45,EU
...,...,...,...,...,...,...,...,...,...,...,...
110,Switzerland,8860574,35.00,38.00,8.00,4.00,6.00,7.00,1.00,1.00,EU
115,Turkey,84119531,29.40,38.30,13.20,6.40,4.40,5.50,2.10,0.70,AS
117,Ukraine,35661826,32.00,34.00,15.00,5.00,5.00,6.00,2.00,1.00,EU
120,United States,341963408,37.40,35.70,8.50,3.40,6.60,6.30,1.50,0.60,NaN
121,Uzbekistan,36520593,29.42,30.93,24.98,9.27,1.68,1.77,1.42,0.53,AS

Find the country with the highest population.

In [55]:
df.loc[df['Population'].idxmax(), 'Country']

'World'

Find the country with the lowest population.

In [58]:
df.loc[df['Population'].idxmin(), 'Country']

'Liechtenstein'

Find the average population of all countries in the dataset.

In [63]:
df['Population'].mean()

np.float64(122667689.85826771)

Find the average O+ percentage across all countries.

In [64]:
df['O+'].mean()

np.float64(40.42433070866141)

Find the average A+ percentage across all countries.

In [65]:
df['A+'].mean()

np.float64(29.153622047244095)

Find the highest O+ percentage in the dataset.

In [71]:
df['O+'].max()

np.float64(75.0)

Find the country with the lowest A+ percentage.

In [73]:
df.loc[df['A+'].idxmin(), 'Country']

'Ecuador'

Find the average B+ percentage across all countries.

In [74]:
df['B+'].mean()

np.float64(16.28748031496063)

Find the highest B+ percentage in the dataset.

In [75]:
df['B+'].max()

np.float64(36.8)

In [ ]:
Find the country with the highest B+ percentage.

In [76]:
df.loc[df['B+'].idxmax(), 'Country']

'Thailand'

Find the average AB+ percentage across all countries.

In [77]:
df['AB+'].mean()

np.float64(4.679921259842519)

Find the country with the highest AB+ percentage.

In [78]:
df.loc[df['AB+'].idxmax(), 'Country']

'North Korea'

Find the average O- percentage across all countries.

In [79]:
df['O+'].mean()

np.float64(40.42433070866141)

Find the highest O- percentage in the dataset.

In [80]:
df['O-'].max()

np.float64(13.3)

Find the country with the highest O- percentage.

In [82]:
df.loc[df['O-'].idxmax(), 'Country']

'Mongolia'

Find the average A- percentage across all countries.

In [83]:
df['A-'].mean()

np.float64(3.362619047619048)

Find the highest A- percentage in the dataset.

In [84]:
df['A-'].max()

np.float64(9.0)

Find the country with the highest A- percentage.

In [85]:
df.loc[df['A-'].idxmax(), 'Country']

'United Kingdom'

O+ percentage is greater than 40 AND A+ percentage is greater than 30.

In [87]:
df[(df['O+'] > 40) & (df['A+'] > 30)]

,Country,Population,O+,A+,B+,AB+,O-,A-,B-,AB-,Continent
2,Argentina,46994384,50.34,31.09,8.2,2.16,4.29,2.98,0.74,0.2,SA
24,Cuba,10966038,45.80,33.50,10.2,2.90,3.60,2.80,1.00,0.2,NaN
35,Fiji,951611,43.00,33.30,16.5,4.80,1.00,0.70,0.50,0.2,OC
76,Morocco,37387585,42.30,30.80,14.0,4.00,4.50,3.10,1.50,0.4,AF
89,Papua New Guinea,10046233,55.70,32.20,9.6,2.10,1.80,0.50,0.20,0.1,OC

Find all countries where O+ is greater than 40 OR A+ is greater than 30.

In [88]:
df[(df['O+'] > 40) | (df['A+'] > 30)]

,Country,Population,O+,A+,B+,AB+,O-,A-,B-,AB-,Continent
0,Albania,3107100,34.10,31.20,14.50,5.20,6.00,5.50,2.60,0.90,EU
2,Argentina,46994384,50.34,31.09,8.20,2.16,4.29,2.98,0.74,0.20,SA
3,Armenia,2976765,29.00,46.30,12.00,5.60,2.00,3.70,1.00,0.40,AS
4,Australia,26768598,38.00,32.00,12.00,4.00,7.00,6.00,2.00,1.00,OC
5,Austria,8967982,30.00,37.00,12.00,5.00,6.00,7.00,2.00,0.45,EU
...,...,...,...,...,...,...,...,...,...,...,...
121,Uzbekistan,36520593,29.42,30.93,24.98,9.27,1.68,1.77,1.42,0.53,AS
122,Venezuela,31250306,58.30,28.20,5.60,1.90,4.00,1.50,0.40,0.10,SA
123,Vietnam,105758975,41.70,20.90,30.80,4.98,0.30,0.10,0.20,0.02,AS
124,Yemen,32140443,47.84,27.50,15.32,2.14,3.66,2.10,1.17,0.16,AS
125,Zimbabwe,17150352,45.70,28.80,18.00,4.10,1.70,1.00,0.40,0.30,AF

Find all countries where the population is greater than 100 million AND O+ is greater than 35.

In [90]:
df[(df['Population'] > 100000000) & (df['O+'] > 35)]

,Country,Population,O+,A+,B+,AB+,O-,A-,B-,AB-,Continent
14,Brazil,220051512,36.00,34.00,8.00,2.50,9.00,8.00,2.00,0.50,SA
27,Democratic Republic of the Congo,115403027,59.50,21.30,15.20,2.40,1.00,0.30,0.20,0.10,AF
31,Egypt,111247248,36.44,33.94,20.96,8.65,NaN,NaN,NaN,NaN,AF
34,Ethiopia,118550298,39.00,28.00,21.00,5.00,3.00,2.00,1.00,1.00,AF
49,Indonesia,281562465,36.82,25.87,28.85,7.96,0.18,0.13,0.15,0.04,AS
73,Mexico,130739927,59.09,26.23,8.53,1.73,2.73,1.21,0.40,0.08,NaN
83,Nigeria,236747130,50.23,21.61,19.59,3.47,2.70,1.16,1.05,0.19,AF
92,Philippines,118277063,45.90,22.90,24.90,5.97,0.10,0.10,0.10,0.03,AS
97,Russia,140820810,36.00,31.00,19.00,2.10,6.00,4.00,1.00,0.90,EU
120,United States,341963408,37.40,35.70,8.50,3.40,6.60,6.30,1.50,0.60,NaN
123,Vietnam,105758975,41.70,20.90,30.80,4.98,0.30,0.10,0.20,0.02,AS
126,World,8057236243,38.40,27.30,8.10,2.00,13.10,8.10,2.00,0.01,NaN

Find all countries where Continent = AS AND O+ > 40.

In [96]:
df[(df['Continent'] == 'AS') & (df['O+'] > 40)]

,Country,Population,O+,A+,B+,AB+,O-,A-,B-,AB-,Continent
7,Bahrain,1566888,48.48,15.35,22.61,3.67,3.27,1.33,1.04,0.25,AS
17,Cambodia,17063669,46.70,27.20,18.50,4.90,1.30,0.80,0.50,0.10,AS
45,Hong Kong,7297821,42.80,25.50,25.80,5.90,0.70,0.10,0.20,0.10,AS
68,Macao,644426,41.50,26.10,25.40,6.30,0.33,0.09,0.17,0.05,AS
87,Oman,3901992,44.90,17.40,20.20,6.80,7.40,0.60,2.70,NaN,AS
92,Philippines,118277063,45.90,22.90,24.90,5.97,0.10,0.10,0.10,0.03,AS
98,Saudi Arabia,36544431,47.80,16.00,17.90,4.00,4.00,2.00,1.00,0.30,AS
100,Singapore,6028459,44.70,23.90,24.50,5.60,0.60,0.30,0.30,0.10,AS
107,Sri Lanka,21982608,43.42,21.00,25.78,5.13,2.12,1.04,1.25,0.26,AS
111,Syria,23865423,43.00,30.00,14.00,3.70,5.00,3.00,1.00,0.30,AS
112,Taiwan,23595274,43.90,25.90,23.90,6.00,0.28,0.01,0.01,0.01,AS
113,Thailand,69920998,40.80,16.90,36.80,4.97,0.20,0.10,0.20,0.03,AS
118,United Arab Emirates,10032213,44.10,21.90,20.90,4.30,4.30,2.10,2.00,0.40,AS
123,Vietnam,105758975,41.70,20.90,30.80,4.98,0.30,0.10,0.20,0.02,AS
124,Yemen,32140443,47.84,27.50,15.32,2.14,3.66,2.10,1.17,0.16,AS

Find all countries where Population > 50 million.

In [98]:
df.loc[df['Population'] > 50000000, 'Country']

8                            Bangladesh
14                               Brazil
27     Democratic Republic of the Congo
31                                Egypt
34                             Ethiopia
37                               France
40                              Germany
48                                India
49                            Indonesia
50                                 Iran
54                                Italy
57                                Japan
60                                Kenya
73                               Mexico
77                              Myanmar
83                              Nigeria
88                             Pakistan
92                          Philippines
95           People's Republic of China
97                               Russia
104                        South Africa
105                         South Korea
108                               Sudan
113                            Thailand
115                              Turkey
119                      United Kingdom
120                       United States
123                             Vietnam
126                               World
Name: Country, dtype: str

Find countries where: A+ < 25 AND O+ > 35.

In [99]:
df[(df['A+'] < 25) & (df['O+'] > 35)]

,Country,Population,O+,A+,B+,AB+,O-,A-,B-,AB-,Continent
7,Bahrain,1566888,48.48,15.35,22.61,3.67,3.27,1.33,1.04,0.25,AS
12,Bolivia,12311974,51.53,20.45,10.11,1.15,4.39,2.73,0.54,0.10,SA
16,Burkina Faso,23042199,39.94,20.79,26.34,5.17,3.36,1.75,2.22,0.43,AF
18,Cameroon,30966105,46.83,24.15,21.06,4.29,1.79,0.92,0.80,0.16,AF
21,Colombia,49588357,61.30,21.11,7.28,1.47,5.13,2.70,0.70,0.31,SA
27,Democratic Republic of the Congo,115403027,59.50,21.30,15.20,2.40,1.00,0.30,0.20,0.10,AF
30,Ecuador,18309984,75.00,14.00,7.10,0.50,2.38,0.70,0.30,0.02,SA
32,El Salvador,6628702,62.00,23.00,11.00,1.00,1.00,1.00,0.70,0.30,NaN
38,Gabon,2455105,57.55,20.52,17.19,2.54,1.35,0.48,0.41,0.06,AF
41,Ghana,34589092,53.80,17.60,18.30,2.80,4.50,1.30,1.30,0.20,AF
43,Guinea,13986179,46.88,21.64,22.86,4.52,2.00,0.90,1.00,0.20,AF
55,Ivory Coast,29981758,47.24,20.19,21.70,3.82,3.73,1.54,1.48,0.30,AF
56,Jamaica,2823713,51.10,20.00,20.00,1.90,3.50,2.00,1.00,0.50,NaN
61,Laos,7953556,37.52,19.73,35.36,6.85,0.20,0.10,0.20,0.05,AS
64,Libya,7361263,42.64,20.86,11.19,4.50,7.26,3.24,1.64,0.67,AF
77,Myanmar,57527139,35.70,23.80,32.70,6.95,0.30,0.20,0.30,0.05,AS
78,Namibia,2803660,50.58,20.49,20.21,1.02,4.22,1.71,1.69,0.08,AF
82,Nicaragua,6676948,62.00,20.00,11.00,4.00,1.00,1.00,0.70,0.30,NaN
83,Nigeria,236747130,50.23,21.61,19.59,3.47,2.70,1.16,1.05,0.19,AF
87,Oman,3901992,44.90,17.40,20.20,6.80,7.40,0.60,2.70,NaN,AS
90,Paraguay,7522549,63.07,21.32,4.72,1.38,5.89,2.97,0.49,0.15,SA
91,Peru,32600249,70.00,18.40,7.80,1.60,1.40,0.50,0.28,0.02,SA
92,Philippines,118277063,45.90,22.90,24.90,5.97,0.10,0.10,0.10,0.03,AS
98,Saudi Arabia,36544431,47.80,16.00,17.90,4.00,4.00,2.00,1.00,0.30,AS
100,Singapore,6028459,44.70,23.90,24.50,5.60,0.60,0.30,0.30,0.10,AS
103,Somalia,13017273,52.80,19.36,12.32,3.52,7.20,2.64,1.68,0.48,AF
107,Sri Lanka,21982608,43.42,21.00,25.78,5.13,2.12,1.04,1.25,0.26,AS
113,Thailand,69920998,40.80,16.90,36.80,4.97,0.20,0.10,0.20,0.03,AS
116,Uganda,49283041,49.29,24.11,20.29,4.41,1.01,0.49,0.41,0.09,AF
118,United Arab Emirates,10032213,44.10,21.90,20.90,4.30,4.30,2.10,2.00,0.40,AS
123,Vietnam,105758975,41.70,20.90,30.80,4.98,0.30,0.10,0.20,0.02,AS

Sort the dataset by Population from highest to lowest.

In [101]:
df.sort_values('Population', ascending = False)

,Country,Population,O+,A+,B+,AB+,O-,A-,B-,AB-,Continent
126,World,8057236243,38.40,27.30,8.10,2.00,13.10,8.10,2.00,0.01,NaN
95,People's Republic of China,1416043270,34.00,27.60,28.90,8.40,0.40,0.25,0.20,0.15,AS
48,India,1409128296,32.53,21.80,32.10,7.70,2.03,1.36,2.00,0.48,AS
120,United States,341963408,37.40,35.70,8.50,3.40,6.60,6.30,1.50,0.60,NaN
49,Indonesia,281562465,36.82,25.87,28.85,7.96,0.18,0.13,0.15,0.04,AS
...,...,...,...,...,...,...,...,...,...,...,...
67,Luxembourg,671254,35.00,37.00,9.00,4.00,6.00,6.00,2.00,1.00,EU
68,Macao,644426,41.50,26.10,25.40,6.30,0.33,0.09,0.17,0.05,AS
70,Malta,469730,38.00,41.00,7.00,3.00,5.00,4.50,1.00,0.50,EU
47,Iceland,364036,46.80,27.20,9.00,2.00,8.20,4.80,1.60,0.40,EU
65,Liechtenstein,40272,34.00,37.00,10.00,4.00,6.00,6.50,1.80,0.70,EU

Sort the entire dataset by O+ percentage from highest to lowest.

In [102]:
df.sort_values('O+', ascending = False)

,Country,Population,O+,A+,B+,AB+,O-,A-,B-,AB-,Continent
30,Ecuador,18309984,75.00,14.00,7.10,0.50,2.38,0.70,0.30,0.02,SA
91,Peru,32600249,70.00,18.40,7.80,1.60,1.40,0.50,0.28,0.02,SA
90,Paraguay,7522549,63.07,21.32,4.72,1.38,5.89,2.97,0.49,0.15,SA
32,El Salvador,6628702,62.00,23.00,11.00,1.00,1.00,1.00,0.70,0.30,NaN
82,Nicaragua,6676948,62.00,20.00,11.00,4.00,1.00,1.00,0.70,0.30,NaN
...,...,...,...,...,...,...,...,...,...,...,...
36,Finland,5626414,28.00,35.00,16.00,7.00,5.00,6.00,2.00,1.00,EU
101,Slovakia,5563649,27.20,35.70,15.30,6.80,4.80,6.30,2.70,1.20,EU
84,North Korea,26298666,27.15,31.08,30.15,11.32,0.08,0.10,0.10,0.03,AS
46,Hungary,9855745,27.00,33.00,16.00,8.00,5.00,7.00,3.00,1.00,EU
26,Czech Republic,10837890,27.00,36.00,15.00,7.00,5.00,6.00,3.00,1.00,EU

Sort the entire dataset by A+ percentage from lowest to highest.

In [103]:
df.sort_values('A+', ascending = True)

,Country,Population,O+,A+,B+,AB+,O-,A-,B-,AB-,Continent
30,Ecuador,18309984,75.00,14.00,7.10,0.50,2.38,0.70,0.30,0.02,SA
7,Bahrain,1566888,48.48,15.35,22.61,3.67,3.27,1.33,1.04,0.25,AS
98,Saudi Arabia,36544431,47.80,16.00,17.90,4.00,4.00,2.00,1.00,0.30,AS
113,Thailand,69920998,40.80,16.90,36.80,4.97,0.20,0.10,0.20,0.03,AS
87,Oman,3901992,44.90,17.40,20.20,6.80,7.40,0.60,2.70,NaN,AS
...,...,...,...,...,...,...,...,...,...,...,...
57,Japan,123201945,29.90,39.80,19.90,9.90,0.15,0.20,0.10,0.05,AS
25,Cyprus,1320525,35.22,40.35,11.11,4.72,3.85,3.48,0.87,0.40,AS
70,Malta,469730,38.00,41.00,7.00,3.00,5.00,4.50,1.00,0.50,EU
86,Norway,5509733,33.20,41.60,6.80,3.40,5.80,7.40,1.20,0.60,EU
3,Armenia,2976765,29.00,46.30,12.00,5.60,2.00,3.70,1.00,0.40,AS

Find the average O+ percentage for each continent.

In [104]:
df.groupby("Continent")['O+'].mean()

Continent
AF    46.077391
AS    37.167073
EU    33.482564
OC    43.675000
SA    57.838889
Name: O+, dtype: float64

Find the average A+ percentage for each continent.

In [106]:
df.groupby('Continent')['A+'].mean()

Continent
AF    24.780435
AS    27.619512
EU    34.676410
OC    32.375000
SA    24.072222
Name: A+, dtype: float64

Find the average population for each continent.

In [107]:
df.groupby('Continent')['Population'].mean()

Continent
AF    4.686250e+07
AS    1.136705e+08
EU    1.894372e+07
OC    1.073191e+07
SA    4.858822e+07
Name: Population, dtype: float64

Find the number of countries in each continent.

In [108]:
df.groupby('Continent')['Country'].count()

Continent
AF    23
AS    41
EU    39
OC     4
SA     9
Name: Country, dtype: int64

Create a new column called Total_Positive.

It should contain:

O+ + A+ + B+ + AB+

In [110]:
df['Total_Positive'] = df['O+'] + df['A+'] + df['B+'] + df['AB+']

Create a new column called Total_Negative containing:

O- + A- + B- + AB-

In [111]:
df['Total_Negative'] = df['O-'] + df['A-'] + df['B-'] + df['AB-']

Now compare positive vs negative blood types.

Create a new column called Positive_Minus_Negative:

In [112]:
df['Positive_Minus_Negative'] = df['Total_Positive'] - df['Total_Negative']

Create a pivot table showing the average blood-type percentage for each continent.

In [117]:
pivot = df.pivot_table(
    index = 'Continent',
    values = ['O+', 'A+', 'B+', 'AB+', 'O-', 'A-', 'B-', 'AB-'],
    aggfunc = 'mean'
)
pivot

,A+,A-,AB+,AB-,B+,B-,O+,O-
Continent,,,,,,,,
AF,24.780435,1.728182,4.046087,0.344545,18.371304,1.150000,46.077391,3.448182
AS,27.619512,1.761463,6.424146,0.289500,23.058780,1.067073,37.167073,2.487317
EU,34.676410,6.203077,4.679487,0.862821,11.887179,2.076923,33.482564,6.007179
OC,32.375000,3.300000,3.475000,0.433333,12.025000,0.925000,43.675000,4.700000
SA,24.072222,2.691111,1.607778,0.171111,7.425556,0.673333,57.838889,4.518889

Find the average population for each continent using groupby().

In [120]:
df.groupby('Continent')['Population'].mean()

Continent
AF    4.686250e+07
AS    1.136705e+08
EU    1.894372e+07
OC    1.073191e+07
SA    4.858822e+07
Name: Population, dtype: float64

Find all countries where:

Population > 50 million AND Total_Positive > 60

In [121]:
df[(df['Population'] > 50000000) & (df['Total_Positive'] > 60)]

,Country,Population,O+,A+,B+,AB+,O-,A-,B-,AB-,Continent,Total_Positive,Total_Negative,Positive_Minus_Negative
8,Bangladesh,168697184,29.21,26.30,33.12,9.59,0.53,0.48,0.60,0.17,AS,98.22,1.78,96.44
14,Brazil,220051512,36.00,34.00,8.00,2.50,9.00,8.00,2.00,0.50,SA,80.50,19.50,61.00
27,Democratic Republic of the Congo,115403027,59.50,21.30,15.20,2.40,1.00,0.30,0.20,0.10,AF,98.40,1.60,96.80
31,Egypt,111247248,36.44,33.94,20.96,8.65,NaN,NaN,NaN,NaN,AF,99.99,NaN,NaN
34,Ethiopia,118550298,39.00,28.00,21.00,5.00,3.00,2.00,1.00,1.00,AF,93.00,7.00,86.00
37,France,68374591,36.50,38.20,7.70,2.50,6.50,6.80,1.40,0.40,EU,84.90,15.10,69.80
40,Germany,84119100,35.00,37.00,9.00,4.00,6.00,6.00,2.00,1.00,EU,85.00,15.00,70.00
48,India,1409128296,32.53,21.80,32.10,7.70,2.03,1.36,2.00,0.48,AS,94.13,5.87,88.26
49,Indonesia,281562465,36.82,25.87,28.85,7.96,0.18,0.13,0.15,0.04,AS,99.50,0.50,99.00
50,Iran,88386937,36.50,27.00,22.20,4.00,5.00,2.00,2.50,0.80,AS,89.70,10.30,79.40
54,Italy,60964931,39.00,36.00,7.50,2.50,7.00,6.00,1.50,0.50,EU,85.00,15.00,70.00
57,Japan,123201945,29.90,39.80,19.90,9.90,0.15,0.20,0.10,0.05,AS,99.50,0.50,99.00
60,Kenya,58246378,45.60,25.20,21.28,4.20,1.80,1.00,0.90,0.02,AF,96.28,3.72,92.56
73,Mexico,130739927,59.09,26.23,8.53,1.73,2.73,1.21,0.40,0.08,NaN,95.58,4.42,91.16
77,Myanmar,57527139,35.70,23.80,32.70,6.95,0.30,0.20,0.30,0.05,AS,99.15,0.85,98.30
83,Nigeria,236747130,50.23,21.61,19.59,3.47,2.70,1.16,1.05,0.19,AF,94.90,5.10,89.80
88,Pakistan,252363571,30.04,21.53,30.24,8.83,3.10,2.22,3.13,0.91,AS,90.64,9.36,81.28
92,Philippines,118277063,45.90,22.90,24.90,5.97,0.10,0.10,0.10,0.03,AS,99.67,0.33,99.34
95,People's Republic of China,1416043270,34.00,27.60,28.90,8.40,0.40,0.25,0.20,0.15,AS,98.90,1.00,97.90
97,Russia,140820810,36.00,31.00,19.00,2.10,6.00,4.00,1.00,0.90,EU,88.10,11.90,76.20
104,South Africa,60442647,39.00,32.00,12.00,3.00,6.00,5.00,2.00,1.00,AF,86.00,14.00,72.00
105,South Korea,52081799,29.00,32.00,31.00,8.00,0.19,0.10,0.10,0.01,AS,100.00,0.40,99.60
108,Sudan,50467278,48.00,27.70,15.20,2.30,3.50,1.80,0.80,0.20,AF,93.20,6.30,86.90
113,Thailand,69920998,40.80,16.90,36.80,4.97,0.20,0.10,0.20,0.03,AS,99.47,0.53,98.94
115,Turkey,84119531,29.40,38.30,13.20,6.40,4.40,5.50,2.10,0.70,AS,87.30,12.70,74.60
119,United Kingdom,68459055,36.00,30.00,8.00,2.00,8.00,9.00,2.00,1.00,EU,76.00,20.00,56.00
120,United States,341963408,37.40,35.70,8.50,3.40,6.60,6.30,1.50,0.60,NaN,85.00,15.00,70.00
123,Vietnam,105758975,41.70,20.90,30.80,4.98,0.30,0.10,0.20,0.02,AS,98.38,0.62,97.76
126,World,8057236243,38.40,27.30,8.10,2.00,13.10,8.10,2.00,0.01,NaN,75.80,23.21,52.59

Find the average Total_Positive and average Total_Negative for the whole dataset.

In [125]:
avg_TP = df['Total_Positive'].mean()
avg_TN = df['Total_Negative'].mean()
print(avg_TP)
print(avg_TN)

90.54535433070866
9.250483870967741

Fill all missing values in the A+ column with its average value.

In [ ]:
df['A+'] = df['A+'].fillna(df['A+'].mean())

Remove all rows where A+ is missing.

In [128]:
df.dropna(subset = ['A+'])

,Country,Population,O+,A+,B+,AB+,O-,A-,B-,AB-,Continent,Total_Positive,Total_Negative,Positive_Minus_Negative
0,Albania,3107100,34.10,31.20,14.50,5.20,6.00,5.50,2.60,0.90,EU,85.00,15.00,70.00
1,Algeria,47022473,40.00,30.00,15.00,4.25,6.60,2.30,1.10,0.75,AF,89.25,10.75,78.50
2,Argentina,46994384,50.34,31.09,8.20,2.16,4.29,2.98,0.74,0.20,SA,91.79,8.21,83.58
3,Armenia,2976765,29.00,46.30,12.00,5.60,2.00,3.70,1.00,0.40,AS,92.90,7.10,85.80
4,Australia,26768598,38.00,32.00,12.00,4.00,7.00,6.00,2.00,1.00,OC,86.00,16.00,70.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,Venezuela,31250306,58.30,28.20,5.60,1.90,4.00,1.50,0.40,0.10,SA,94.00,6.00,88.00
123,Vietnam,105758975,41.70,20.90,30.80,4.98,0.30,0.10,0.20,0.02,AS,98.38,0.62,97.76
124,Yemen,32140443,47.84,27.50,15.32,2.14,3.66,2.10,1.17,0.16,AS,92.80,7.09,85.71
125,Zimbabwe,17150352,45.70,28.80,18.00,4.10,1.70,1.00,0.40,0.30,AF,96.60,3.40,93.20
126,World,8057236243,38.40,27.30,8.10,2.00,13.10,8.10,2.00,0.01,NaN,75.80,23.21,52.59